meta:
  title: Test Driven Development (TDD)
  thumbnail: https://avatars0.githubusercontent.com/u/11692854?s=460&v=4
  description: Test Driven Development (TDD)
  sns:
    - twitter
slide:
  loop: false 
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js:
  css: ./style.css
  webpack:
build:
  ssr: true
